version: 0.2

env:
  parameter-store:
  variables: {}

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT.dkr.ecr.$REGION.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY .
      - docker tag $REPOSITORY:latest $ACCOUNT.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY:latest

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $ACCOUNT.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY:latest
      - echo Build completed on `date`
